### ISSUE TITLE
M1芯片打开失败

### ISSUE THREAD

**Issue by PandexLee** [9t5c/pixel-loss#6]
MacBook Air M1, 2020
macOS 13.1 (22C65)

解决完“应用已损坏”的问题后，打开APP是一个大的提示框。

![image](https://user-images.githubusercontent.com/14109212/217727953-ac96f9c2-df23-4f28-b0e1-23f4f9f3c1b1.png)

**Comment by 9t5c** [comment]
久等了，已支持 Apple silicon，请到 Releases 下载最新的版本。
